// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "hello_world.proto" (package "hello_world", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Greeter } from "./hello_world";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloReply } from "./hello_world";
import type { HelloRequest } from "./hello_world";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service hello_world.Greeter
 */
export interface IGreeterClient {
    /**
     * @generated from protobuf rpc: SayHello(hello_world.HelloRequest) returns (hello_world.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply>;
    /**
     * @generated from protobuf rpc: SayHelloStreamReply(hello_world.HelloRequest) returns (stream hello_world.HelloReply);
     */
    sayHelloStreamReply(input: HelloRequest, options?: RpcOptions): ServerStreamingCall<HelloRequest, HelloReply>;
}
/**
 * @generated from protobuf service hello_world.Greeter
 */
export class GreeterClient implements IGreeterClient, ServiceInfo {
    typeName = Greeter.typeName;
    methods = Greeter.methods;
    options = Greeter.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SayHello(hello_world.HelloRequest) returns (hello_world.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SayHelloStreamReply(hello_world.HelloRequest) returns (stream hello_world.HelloReply);
     */
    sayHelloStreamReply(input: HelloRequest, options?: RpcOptions): ServerStreamingCall<HelloRequest, HelloReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloReply>("serverStreaming", this._transport, method, opt, input);
    }
}
